# Generated by Django 5.2.7 on 2025-11-08 09:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название шаблона')),
                ('template', models.TextField(verbose_name='Шаблон промпта')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Шаблон промпта',
                'verbose_name_plural': 'Шаблоны промптов',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('fullName', models.CharField(max_length=255, verbose_name='Полное имя')),
                ('role', models.CharField(choices=[('ADMIN', 'Администратор'), ('EMPLOYEE', 'Сотрудник')], default='EMPLOYEE', max_length=20, verbose_name='Роль')),
                ('dateJoined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации')),
                ('isActive', models.BooleanField(default=True, verbose_name='Активен')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=255, verbose_name='Действие')),
                ('model_name', models.CharField(max_length=255, verbose_name='Модель')),
                ('object_id', models.CharField(max_length=255, verbose_name='ID объекта')),
                ('details', models.JSONField(default=dict, verbose_name='Детали')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог аудита',
                'verbose_name_plural': 'Логи аудита',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название чата')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('isActive', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_temporary', models.BooleanField(default=False, verbose_name='Временный')),
                ('temp_created_at', models.DateTimeField(blank=True, null=True, verbose_name='Время создания временного чата')),
                ('flow_step', models.IntegerField(default=0, verbose_name='Текущий шаг flow')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='Содержание')),
                ('messageType', models.CharField(choices=[('SYSTEM', 'Системное'), ('USER', 'Пользовательское')], default='USER', max_length=20, verbose_name='Тип сообщения')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.chat', verbose_name='Чат')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['createdAt'],
            },
        ),
        migrations.CreateModel(
            name='PromptHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assembled_prompt', models.TextField(verbose_name='Собранный промпт')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_history', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История промптов',
                'verbose_name_plural': 'История промптов',
            },
        ),
        migrations.CreateModel(
            name='MediaGenerationTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt_text', models.TextField(verbose_name='Текст промпта')),
                ('status', models.CharField(choices=[('PENDING', 'В ожидании'), ('RUNNING', 'Выполняется'), ('SUCCESS', 'Успешно'), ('FAILED', 'Ошибка')], default='PENDING', max_length=20, verbose_name='Статус')),
                ('result_url', models.URLField(blank=True, null=True, verbose_name='URL результата')),
                ('attempts', models.IntegerField(default=0, verbose_name='Попытки')),
                ('last_error', models.TextField(blank=True, null=True, verbose_name='Последняя ошибка')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.chat', verbose_name='Чат')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('prompt_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.prompthistory', verbose_name='История промпта')),
            ],
            options={
                'verbose_name': 'Задача генерации',
                'verbose_name_plural': 'Задачи генерации',
            },
        ),
        migrations.CreateModel(
            name='PromptParameters',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField(default=dict, verbose_name='Параметры')),
                ('semantic_vector', models.JSONField(default=dict, verbose_name='Семантический вектор')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_parameters', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Параметры промпта',
                'verbose_name_plural': 'Параметры промптов',
            },
        ),
        migrations.AddField(
            model_name='prompthistory',
            name='parameters',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.promptparameters', verbose_name='Параметры'),
        ),
        migrations.AddField(
            model_name='prompthistory',
            name='prompt_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.prompttemplate', verbose_name='Шаблон промпта'),
        ),
    ]
